-- Add new fields to company table for profile completion
ALTER TABLE company ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE company ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE company ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE company ADD COLUMN IF NOT EXISTS about TEXT;
ALTER TABLE company ADD COLUMN IF NOT EXISTS company_size VARCHAR(50);
ALTER TABLE company ADD COLUMN IF NOT EXISTS founded_year INT;
ALTER TABLE company ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255);
ALTER TABLE company ADD COLUMN IF NOT EXISTS logo VARCHAR(255);
ALTER TABLE company ADD COLUMN IF NOT EXISTS profile_completed TINYINT(1) DEFAULT 0;
